### ISSUE TITLE
Feature: StoreMgr Homepage-My Products

### ISSUE THREAD

**Issue by catyber** [catyber/storeMgr#11]
# Epic Title

Feature: StoreMgr Homepage-My Products

## Epic Description

This Feature will implement My Products tab in Home page

## List of Tasks (Complete in order)

- [ ] Task: UI MyProducts tab catyber/storeMgr#8
- [ ] Task: Add Products catyber/storeMgr#7
- [ ] Task: View Products catyber/storeMgr#6
- [ ] Task: Update Products catyber/storeMgr#5
- [ ] Task: Delete Products catyber/storeMgr#4
