### ISSUE TITLE
Feature: StoreMgr Home Page-My Store

### ISSUE THREAD

**Issue by catyber** [catyber/storeMgr#15]
# Epic Title

Feature: StoreMgr Home Page-My Store

## Epic Description

This Feature will implement My Store tab of Home page

## List of Tasks (Complete in order)

- [ ] Task: UI MyStore tab catyber/storeMgr#14
- [ ] Task: MyStore data retrieval catyber/storeMgr#13
- [ ] Task: MyStore data update catyber/storeMgr#12
