### ISSUE TITLE
Feature: Website security

### ISSUE THREAD

**Issue by catyber** [catyber/storeMgr#22]
# Epic Title

Feature: Website security

## Epic Description

This Feature will implement Login/Logout/Register using JWT Authentication

## List of Tasks (Complete in order)

- [x] Task: Models for security feature catyber/storeMgr#21
- [x] Task: Webapp security REST endpoints catyber/storeMgr#20
- [ ] Task: UI Public/Login Page catyber/storeMgr#19
